name: update-data-beta
on: 
  repository_dispatch:
    types: [update-data]

jobs:
  update-data-beta:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.branch }}
        
      - run: git config --global user.email "andrew@centersforcivicimpact.org"
      - run: git config --global user.name "Automated Data Update"

      - name: use nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: install dependencies
        run: npm ci

      - name: download data from airtable
        env: 
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
        run: node scripts/airtable-downloader.js

      - name: generate new data file for website
        run: |
          node scripts/generate-website-data-files.js
          node scripts/authority-policy-position-timeseries.js static/data/comit-v1.min.json
          node scripts/country-policy-position-timeseries.js static/data/comit-v1.min.json

      - name: add data files to commit
        run: git add static/data/comit-v1.min.json static/data/comit-v1.csv

      - name: commit changes to git
        run: git commit -m "automated data update"

      - name: push data update
        run: git push

      - name: deploy to heroku
        if: ${{ (github.event.client_payload.branch == 'beta') || (github.event.client_payload.branch == 'production') }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_app_name: ivac-comitglobal-beta
          branch: ${{ github.event.client_payload.branch }}

      - name: send job status back to airtable
        if: ${{ always() }}
        uses: jasongitmail/fast-webhook@v1
        with:
          url: ${{ github.event.client_payload.callbackUrl }}
          json: '{"action-output": {"status": "${{ job.status }}", "recordId": "${{ github.event.client_payload.recordId }}", "environment": "${{ github.event.client_payload.branch }}"}}'

