name: update-data-beta
on: 
  workflow_dispatch:

jobs:
  update-data-beta:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - run: git config --global user.email "andrew@centersforcivicimpact.org"
      - run: git config --global user.name "Automated Data Update"

      - name: use nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: install dependencies
        run: npm ci

      - name: download data from airtable
        env: 
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
        run: node scripts/airtable-downloader.js

      - name: generate new data file for website
        run: node scripts/generate-website-data-files.js

      - name: add data file to commit
        run: git add static/data/comit-v1.min.json

      - name: commit changes to git
        run: git commit -m "automated data update"

      - name: push data update
        run: git push
